import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>My Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="avatar-wrapper" >
        <span className="avatar-tooltip">Sliced by Mentari</span>
        <img src="/avatar.svg" className="avatar" alt="avatar roket"></img>
      </div>
      <div className="wrapper">
        <div className="topnav">
          <div className="center-topnav">
            <div className="topnav-wrapper">
              <div className="logo">
                <img src="/logo.svg" className="logo" alt="logo"></img>
              </div>
              <div className="topnav-items">
                <a href="" className="btn-topnav">
                  <img src="/icon-stat.svg" className="icon"></img>Report
                </a>
                <a href="" className="btn-topnav">
                  <img src="/icon-setting.svg" className="icon"></img>Setting
                </a>
                <a href="" className="btn-topnav">
                <img src="/icon-user-circle.svg" className="icon"></img>Login
                </a>
              </div>
            </div>
          </div>
          <div className="progress-bar"></div>
        </div>
        <div className="content">
          <div className="time-content">
            <nav className="time-navbar">
              <a href="" className="btn-nav active">Pomodoro</a>
              <a href="" className="btn-nav">Short Break</a>
              <a href="" className="btn-nav">Long Break</a>
            </nav>
            <div className="clock">
              25:00
            </div>
            <button type="submit" className="start-button">Start</button>
          </div>
        </div>
        <div className="task-list">
          <div className="center-task-list">
            <div className="counter">#1</div>
            <div className="task-title">Time to focus!</div>
            <div className="task-setting">
              <div className="task-setting-title">Task List</div>
              <div className="task-setting-menu"><a href=""><img src="/icon-menu-w.svg"></img></a></div>
            </div>
            <div className="progress-bar"></div>
            <div className="task-card">
                <div className="task-card-ornament"></div>
              <div className="task-card-wrapper">
                <a href=""><img src="/icon-unchecked.svg" className="icon-check"></img></a>
                <h4>Slicing Frontend</h4>
                <h3>1/1</h3>
                <div className=""><a href=""><img src="/icon-menu-b.svg"></img></a></div>
              </div>
            </div>
            <div className="task-add-card">
              <a href="">
                <img src="/icon-add.svg" className="icon-add"></img>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
