import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <img src="/avatar.svg" class="avatar"></img>
      </div>
      <div class="wrapper">
        <div class="topnav">
          <div class="center-topnav">
            <div class="topnav-wrapper">
              <div class="logo">
                <img src="/logo.svg" className="logo" alt="logo"></img>
              </div>
              <div class="topnav-items">
                <a href="" class="btn-topnav">
                  <img src="/icon-stat.svg" className="icon"></img>Report
                </a>
                <a href="" class="btn-topnav">
                  <img src="/icon-setting.svg" className="icon"></img>Setting
                </a>
                <a href="" class="btn-topnav">
                <img src="/icon-user-circle.svg" className="icon"></img>Login
                </a>
              </div>
            </div>
          </div>
          <div className="progress-bar"></div>
        </div>
        <div class="content">
          <div class="time-content">
            <nav class="time-navbar">
              <a href="" class="btn-nav active">Pomodoro</a>
              <a href="" class="btn-nav">Short Break</a>
              <a href="" class="btn-nav">Long Break</a>
            </nav>
            <div class="clock">
              25:00
            </div>
            <button type="submit" class="start-button">Start</button>
          </div>
        </div>
        <div class="task-list">
          <div class="center-task-list">
            <div class="counter">#1</div>
            <div class="task-title">Time to focus!</div>
            <div class="task-setting">
              <div class="task-setting-title">Task List</div>
              <div class="task-setting-menu"><a href=""><img src="/icon-menu-w.svg"></img></a></div>
            </div>
            <div className="progress-bar"></div>
            <div class="task-card">
                <div class="task-card-ornament"></div>
              <div class="task-card-wrapper">
                <a href=""><img src="/icon-unchecked.svg" class="icon-check"></img></a>
                <h4>Slicing Frontent</h4>
                <h3>1/1</h3>
                <div class=""><a href=""><img src="/icon-menu-b.svg"></img></a></div>
              </div>
            </div>
            <div class="task-add-card">
              <a href="">
                <img src="/icon-add.svg" class="icon-add"></img>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
